---

- name: Playbook de instalação do Satellite
  hosts: "{{ servidor }}.automation.here"
  tasks:
    - name: Ativa os repositórios do Satellite
      community.general.rhsm_repository:
        name:
          - "rhel-8-for-x86_64-baseos-rpms"
          - "rhel-8-for-x86_64-appstream-rpms"
          - "satellite-{{ versao_satellite }}-for-rhel-8-x86_64-rpms"
          - "satellite-maintenance-{{ versao_satellite }}-for-rhel-8-x86_64-rpms"
        state: "enabled"
      purge: True

    - name: Instala o pacote do Satellite e suas dependências
      loop:
        - "@satellite:el8"
        - "satellite"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: "latest"

    - name: Role de instalação do Satellite
      include_role:
        name: redhat.satellite_operations.installer
      vars:
        satellite_installer_scenario: satellite
        satellite_installer_package: satellite-installer
        satellite_installer_options:
          - "--foreman-initial-organization {{ organizacao_satellite }}"
          - "--foreman-initial-admin-password {{ senha_satellite }}"
