---
- name: Play que adiciona um registro de DNS no IdM
  gather_facts: False
  hosts: localhost
  tasks:
    - name: Tarefa que adiciona um registro de DNS no IdM
      community.general.ipa_dnsrecord:
        ipa_host: "{{ url_idm }}"
        ipa_user: "{{ user_idm }}"
        ipa_pass: "{{ senha_idm }}"
        state: present
        zone_name: "automation.here."
        record_name: "{{ servidor }}.automation.here."
        record_type: "A"
        record_value: "{{ ip_servidor }}"
