---
- name: Play que adiciona um registro de DNS no IdM
  gather_facts: False
  hosts: localhost
  tasks:
    - name: Tarefa que adiciona um registro de DNS no IdM
      community.general.ipa_dnsrecord:
        ipa_host: "{{ url_idm }}"
        ipa_user: "{{ user_idm }}"
        ipa_pass: "{{ senha_idm }}"
        state: present
        zone_name: "automation.here."
        record_name: "{{ servidor }}"
        record_type: "A"
        record_value: "{{ ip_servidor }}"

- name: Play que registra a máquina no IdM
  gather_facts: True
  hosts: "{{ servidor }}.automation.here"
  tasks:
    - name: Registra a máqunia no IdM
      vars:
        ipaclient_mkhomedir: True
        ipasssd_enable_dns_updates: True
        ipaadmin_password: "{{ senha_idm }}"
      ansible.builtin.include_role:
        name: ipaclient

