---

- name: Define variável intermediária no processo (PARTIAL)
  ansible.builtin.set_fact:
    servidor: "{{ item | regex_search('...-POCVERITAS.') }}"

- name: Alimenta a lista lista_partial
  ansible.builtin.set_fact:
    lista_partial: "{{ lista_partial + [servidor] }}"
