---

- name: Define variável intermediária no processo (ONLINE)
  ansible.builtin.set_fact:
    servidor: "{{ item | regex_search('...-POCVERITAS.') }}"

- name: Alimenta a lista lista_online
  ansible.builtin.set_fact:
    lista_online: "{{ lista_online + [servidor] }}"

